# Generated by Django 5.1.6 on 2025-05-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_reservation_tariff_zone'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE parking_reservation ADD COLUMN tariff_zone_id integer REFERENCES subscriptions_tariffzone(id) ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE parking_reservation DROP COLUMN tariff_zone_id;
            """
        ),
    ]