# Generated by Django 5.1.6 on 2025-05-31 19:33

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_raised', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude1', models.FloatField(blank=True, null=True)),
                ('latitude2', models.FloatField(blank=True, null=True)),
                ('latitude3', models.FloatField(blank=True, null=True)),
                ('latitude4', models.FloatField(blank=True, null=True)),
                ('longitude1', models.FloatField(blank=True, null=True)),
                ('longitude2', models.FloatField(blank=True, null=True)),
                ('longitude3', models.FloatField(blank=True, null=True)),
                ('longitude4', models.FloatField(blank=True, null=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
