# Generated by Django 5.1.6 on 2025-05-31 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='tariff_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_spots', to='subscriptions.tariffzone'),
        ),
        migrations.AddField(
            model_name='blocker',
            name='parking_spot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to='sensor.parkingspot'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='parking_spot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='sensor.parkingspot'),
        ),
    ]
