# Generated by Django 5.1.6 on 2025-06-04 02:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpotOccupancyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_occupied', models.BooleanField()),
                ('day_of_week', models.IntegerField()),
                ('hour_of_day', models.IntegerField()),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_history', to='sensor.parkingspot')),
            ],
            options={
                'verbose_name_plural': 'Parking spot occupancy histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ParkingAvailabilityPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.DateTimeField()),
                ('probability_available', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_predictions', to='sensor.parkingspot')),
            ],
            options={
                'verbose_name_plural': 'Parking availability predictions',
                'ordering': ['prediction_time'],
            },
        ),
    ]